package com.ebifry.barcode.repository

val restricted= arrayOf("Apple","アップル","Beats","ビーツ","BenQ Japan","ベンキュージャパン","Brother","ブラザー","Canon","キャノン","Casio","カシオ","DJI","ディージェーアイ","ELECOM","エレコム","EPSON","エプソン","Fhilips","フィリップス","FUJIFILM","フジフィルム","GoPro","ゴープロ","Microsoft","マイクロソフト","NIKON","ニコン","OLYMPUS","オリンパス","Panasonic","パナソニック","PENTAX","ペンタックス","RICOH","リコー","THERMOS","サーモス","SanDisc","サンディスク","SIGMA","シグマ","SONY","ソニー","Shop Japan","ショップジャパン","TAMRON","タムロン","YAMAHA","ヤマハ","Tanita","タニタ","象印","ゾウジルシ","Bandai","バンダイ","Ergobaby","エルゴベビー","GOOD SMILE COMPANY","グッドスマイルカンパニー","Hoppetta","ホッペタ","LEGO","レゴ","Peeple","ピープル","SEGA TOYS","セガトイズ","STUDIO GHIBLI","スタジオジブリ","TAKARA TOMY","タカラトミー","A BATHING APE","ア・ベイシング・エイプ","Abercrombie & Fitch","アバクロンビー＆フィッチ","adidas","アディダス","BOTTEGA VENETA","ボッテガ・ヴェネタ","BURBERRY","バーバリー","CALVIN KLEIN","カルバンクライン","CANADA GOOSE カナダグース","CHAN LUU","チャン・ルー","Chloe","クロエ","Christian Louboutin","クリスチャン・ルブタン","COACH","コーチ","Daniel Wellington","ダニエル・ウェリントン","Dior","ディオール","Dunhill","ダンヒル","Ed Hardy","エド・ハーディ","emu","エミュー","FENDI","フェンディ","FJALL RAVEN","","フェールラーベン","Giorgio Armani","","ジョルジオ・アルマーニ","GOYARD","ゴヤール","GUCCI","グッチ","GUESSS","ゲス","HUNTER","ハンター","IL BISONTE","イル・ビソンテ","LeSportsac","","レスポートサック","LONGCHAMP","ロンシャン","LOUIS VUITTON","ルイ・ヴィトン","MARC BY MARC JACOBS","マーク・ジェイコブス","Mila schon","ミラ・ショーン","MINNETONKA","ミネトンカ","MONCLER","モンクレール","NEW BALANCE","ニューバランス","NIKE","ナイキ","Orobianco","オロビアンコ","PANERAI","パネライ","Paul Smith","ポール・スミス","Polo Ralph Lauren","","ポロ・ラルフローレン","RAY-BAN","レイバン","Salvatore Ferragamo","","サルヴァトーレ・フェラガモ","TATRAS","タトラス","TIFFANY","ティファニー","TOD’S","トッズ","TOMS SHOES","","トムス・シューズ","TORY BURCH","トリー・バーチ","Vivienne Westwood","ヴィヴィアン・ウエストウッド","VANS","バンズ","Ergobaby","エルゴベビー","Hoppetta","ホッペッタ","Coleman","コールマン","ブランド名","フリガナ","Celvoke","セルヴォーク","ecostore","エコストア","Essie","エッシー","F organics","エッフェオーガニック","giovanni","ジョヴァンニ","HUMBLE BRUSH","ハンブルブラッシュ","LAB SERIES","ラボシリーズ","L’Artisan Parfumeur","ラルチザンパフューム","MDNA SKIN","エムディーエヌエースキン","NYX","ニックス","PENHALIGON’S","ペンハリガン","RANCÉ","ランセ","to/one","トーン","ウォルト・ディズニー・ジャパン株式会社","ウォルト・ディズニー・ジャパン・カブシキガイシャ","COLUMBIA MUSIC ENTERTAINMENT","コロムビアミュージックエンターテイメント","J STORM","ジェーストーム","東宝","トーホウ")
val restrictedCategory= arrayOf("Watch","Jewelry","Grocery","Beauty")
val categoryConst= mapOf(Pair("BISS Basic", "産業・研究開発"),
    Pair("Speakers", "楽器"),
    Pair("Musical Instruments", "楽器"),
    Pair("Pantry Alcohol", "食品・飲料・お酒"),
    Pair("Pantry", "食品・飲料・お酒"),
    Pair("Alcoholic Beverage", "食品・飲料・お酒"),
    Pair("Grocery", "食品・飲料・お酒"),
    Pair("Pharmacy", "薬"),
    Pair("Automotive Parts and Accessories", "カー＆バイク用品"),
    Pair("Shoes", "シューズ＆バッグ"),
    Pair("Pet Products", "ペット用品"),
    Pair("Apparel", "服＆ファッション小物"),
    Pair("Baby Product", "ベビー&マタニティ"),
    Pair("Jewelry", "ジュエリー"),
    Pair("Watch", "時計"),
    Pair("Beauty", "コスメ"),
    Pair("Health and Beauty", "ヘルス&ビューティー"),
    Pair("Sports", "スポーツ&アウトドア"),
    Pair("Hobby", "ホビー"),
    Pair("Toy", "おもちゃ"),
    Pair("Digital Video Games", "TVゲーム"),
    Pair("Video Games", "TVゲーム"),
    Pair("Software", "PCソフト"),
    Pair("Video", "ビデオ"),
    Pair("DVD", "DVD"),
    Pair("Movie", "Amazonビデオ"),
    Pair("Music", "ミュージック"),
    Pair("Home Improvement", "DIY・工具"),
    Pair("Home", "ホーム&キッチン"),
    Pair("Kitchen", "ホーム&キッチン"),
    Pair("Office Product", "文房具・オフィス用品"),
    Pair("Major Appliances", "大型家電"),
    Pair("Photography", "家電&カメラ"),
    Pair("Home Theater", "家電&カメラ"),
    Pair("Personal Computer", "パソコン・周辺機器"),
    Pair("CE", "家電&カメラ"),
    Pair("eBooks", "Kindle"),
    Pair("Book", "本")
)
val categoryFees= mutableMapOf(
    "本" to 0.15,
    "CD・レコード" to 0.08,
    "エレクトロニクス" to 0.08,
    "エレクトロニクス" to 0.08,
    "エレクトロニクス" to 0.08,
    "家電&カメラ" to 0.08,
    "楽器" to 0.08,
    "パソコン・周辺機器" to 0.08,
    "大型家電" to 0.08)

val sellingFees= mutableMapOf(
    465392 to 0.15,
    465392 to 0.15,
    465392 to 0.15,
    465392 to 0.15,
    465392 to 0.15,
    465392 to 0.15,
    465392 to 0.15,
    465392 to 0.15,
    465392 to 0.15,
    465392 to 0.15,
    465392 to 0.15,
    465392 to 0.15,
    465392 to 0.15,
    465392 to 0.15,
    465392 to 0.15
)
